### ISSUE TITLE
[Vue] On SPAs, iframe will not resize

### ISSUE THREAD

**Issue by Kiyo5hi** [giscus/giscus-component#1027]
https://user-images.githubusercontent.com/44930252/214247660-45008532-88ab-407b-92a8-8b01376b4d29.mov

Step to reproduce:

1. Visit https://blog.k1yoshi.com/posts/sample, scroll to the bottom and iframe will render correctly
2. Go to other pages using SPA's routes
3. Come back to the page and scroll to the bottom

**Comment by laymonage** [comment]
Can you please provide a repository where the issue can be reproduced? I noticed this seems to be an issue with Vue supplying a wrong `host` prop instead of leaving it empty, but I cannot reproduce it.

**Comment by Kiyo5hi** [comment]
> Can you please provide a repository where the issue can be reproduced? I noticed this seems to be an issue with Vue supplying a wrong `host` prop instead of leaving it empty, but I cannot reproduce it.

Check `pages/posts/[...slug].vue` in [this repo](https://github.com/Kiyo5hi/blog.k1yoshi.com).

**Comment by Kiyo5hi** [comment]
The problem does get resolved after adopting the workaround provided in #1002. I will close this issue and watch on that problem instead. Thanks!
