### ISSUE TITLE
Wrong theme with loading=lazy

### ISSUE THREAD

**Issue by natario1** [giscus/giscus-component#1152]
Hi,
I'm using the react component as follows:

```javascript
function Comments({ className = '' }) {
  const theme = useGiscusTheme()
  return <Giscus
      ...
      theme={theme}
      loading='lazy'
  />
}
```

If I scroll down and load the comments, then changing the theme works correctly. But if the theme changes before giscus has a chance to load, it won't pick it up and the following error is logged: 

> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://giscus.app') does not match the recipient window's origin ('http://localhost:3002').

Am I doing something wrong?

**Comment by laymonage** [comment]
Could you update to the latest version (v2.2.8) and see if this issue still exists?

**Comment by natario1** [comment]
v2.2.8 fixed the issue. Thank you @laymonage 👏
