### ISSUE TITLE
[VUE] When jumping from a page without comments to a page with comments, giscus does not fully display.

### ISSUE THREAD

**Issue by aiktb** [giscus/giscus-component#1369]
### How to reproduce:

Go to this website and click on "Guide" in the upper right corner
https://strapi-community.github.io/strapi-plugin-rest-cache/

### Display

![Snipaste_2023-04-23_21-51-16](https://user-images.githubusercontent.com/104723527/233843775-cd828da3-6a94-4d61-92f5-6e6c6b2f54db.png)

**Comment by laymonage** [comment]
Same issue as https://github.com/giscus/giscus-component/issues/1370#issuecomment-1519097889.
