### ISSUE TITLE
</p> attempted to close an element that was not open

### ISSUE THREAD

**Issue by NazCodeland** [giscus/giscus-component#1371]
Hello, I am using the svelte Giscus component in my project. I am also using the MDsveX package in my project and I thought originally my issue was related to that package so I opened a ticket there: https://github.com/pngwn/MDsveX/issues/505. 

I've come to learn the issue is due to the HTML custom element `<gitcus-widget>`, not closing itself with an explicit closing tag. It's using the 'shorthand' form, ```<giscus-widget  ... />``` to close itself instead of the `longhand` form, ```<giscus-widget  ... ></giscus-widget>```

 ```svelte
// Giscus.svelte
<script>
  ...
  ...
</script>

{#if mounted}
  <giscus-widget
    {id}
    {host}
    {repo}
    repoid={repoId}
    {category}
    categoryid={categoryId}
    {mapping}
    {term}
    {strict}
    reactionsenabled={reactionsEnabled}
    emitmetadata={emitMetadata}
    inputposition={inputPosition}
    {theme}
    {lang}
    {loading}
  />
{/if}
```
I would like to do a pull request and fix this minor issue. I've read `CONTRIBUTING.md` and I am wondering, since, I am only changing the custom HTML elements to explicitly close, if I also need to follow the instructions in `SELF-HOSTING.md`, or can I contribute without doing the self-hosting? Thanks in advance.

**Comment by laymonage** [comment]
Should be fixed in v2.3.0, please update and confirm. Thanks!
