### ISSUE TITLE
Support Vue 2

### ISSUE THREAD

**Issue by davestewart** [giscus/giscus-component#14]
**Is your feature request related to a problem? Please describe.** 

The lib only supports Vue 3

**Describe the solution you'd like** 

Support Vue 2

**Describe alternatives you've considered**

Writing it myself

**Comment by davestewart** [comment]
I've taken a look at the component which is pretty straightforward to migrate, but the build setup looks more complicated.

Not 100% sure how to get the conflicting versions of vue to work in the same project, with vite.

Happy to push what I have if you want to tackle that bit?

**Comment by davestewart** [comment]
Probably a good idea!

Though I don't know much about them either.

FWIW I forked locally and got it working.

**Comment by laymonage** [comment]
I've released the web component. Those who want to use this library on Vue 2 can use the web component instead (`npm install giscus`). Take a look at [this code](https://github.com/giscus/giscus-component/blob/main/vue/src/lib/Giscus.vue) on how it's used on Vue 3 and adapt accordingly.
