### ISSUE TITLE
lang props support

### ISSUE THREAD

**Issue by leuction** [giscus/giscus-component#15]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

The main giscus support the lang props for multi-language support but it is no available for giscus component version, do we have plan to support them

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

Implement them, I can help on react but I am not familiar with the vue and svelte. 

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

N/A

**Additional context** Add any other context or screenshots about the feature
request here.

N/A

**Comment by robert-orlinski** [comment]
Hey @leuction, I had the same thought as you, so added a little PR with changes to all components (for React, Vue and Svelte). Hope it will be added to the library by the author 🎉 

Meanwhile, if you only want, you can just use my fork of the library which is the source of mentioned PR, that means - which contains multi-language support. Hope it will be useful for you 💪

**Comment by laymonage** [comment]
This has been released in v1.1.0. Thanks!
