### ISSUE TITLE
React build issue

### ISSUE THREAD

**Issue by Tauhid-Ahmed8009** [giscus/giscus-component#1822]
Works fine in the dev state, but after running the build command, the minified version has this error: giscus-1126a0a1.js:15 Uncaught (in promise) ReferenceError: T is not defined quite possibly its this T object that not being recognized: Line 629 of giscus-1126a0a1.js
`  if (o === void 0) {
    const c = (n = e == null ? void 0 : e.renderBefore) !== null && n !== void 0 ? n : null;
    r._$litPart$ = o = new T(t.insertBefore(N(), c), c, void 0, e ?? {});
  }`

**Comment by laymonage** [comment]
How are you using the built package? Running `npm run build`, `npm pack`, and `npm install`-ing the `.tgz` file works fine on my end.

**Comment by Tauhid-Ahmed8009** [comment]
I'm using npm run build the production server is Apache 2.

**Comment by laymonage** [comment]
That does not help... how do you install and use the built package on your project?

**Comment by laymonage** [comment]
I might've misunderstood your question. Did you install the package from npm (e.g. `npm i @giscus/react`), or did you install from source?

**Comment by Tauhid-Ahmed8009** [comment]
I followed official docs npm i @giscus/react

**Comment by Tauhid-Ahmed8009** [comment]
I'd be very grateful if you look into my site and see if you find anything out of the ordinary. all my blogs have the sample repo  that you have added in the docs: just visit this site if  you can: https://tauhid.codes/blogs/5

**Comment by Tauhid-Ahmed8009** [comment]
I meant build on my react app. That i push to production

**Comment by Tauhid-Ahmed8009** [comment]
i managed to get it to work on my production env.  you also need to npm install giscus and import { GiscusWidget } from "giscus"; then after pushing the react build folder to the server i faced no issue.
