### ISSUE TITLE
Height issue

### ISSUE THREAD

**Issue by MartinJohannesNilsen** [giscus/giscus-component#1871]
Hi. I am using the React component version of Giscus on my website. Have a question regarding adding style (min-height 190px? remove overflow?) to the reaction part for not having the popover dissapear in overflow. It is looking like this:

<img width="187" alt="Skjermbilde 2023-11-10 kl  20 08 38" src="https://github.com/giscus/giscus-component/assets/37147119/72cd2967-c418-44fd-9a3b-0c93056bda89">

Any form for help would be greatly appreciated. Cannot find any id, class or argument to the React Component that would indicate a place for style changes.

**Comment by laymonage** [comment]
You can use `giscus-widget::part(iframe)` (or `#comments::part(iframe)` if you've specified an `id` e.g. `comments`)

```css
giscus-widget::part(iframe) {
  min-height: 190px;
}
```

https://github.com/giscus/giscus-component/blob/main/README.md#changing-the-iframe-styles
