### ISSUE TITLE
Doesn't work for Next 14.1.0

### ISSUE THREAD

**Issue by CofCat456** [giscus/giscus-component#1976]
<img width="582" alt="截圖 2024-01-28 下午4 41 26" src="https://github.com/giscus/giscus-component/assets/93901409/92d9f4ff-7f0a-4f00-809f-efe02d8739b8">

Now I'm using the Next version 14.0.4, and it works now.

**Comment by laymonage** [comment]
Probably an issue with Next.js and not giscus: https://github.com/vercel/next.js/issues/61054

**Comment by nicowowblez** [comment]
> 14.0.4

I am using version 14.0.4 but I can't get it to work.

**Comment by sunshihao** [comment]
Is there any solution？

**Comment by laymonage** [comment]
I recently updated my website to use Next.js v14.1 and it works just fine 🤔 

https://github.com/laymonage/base/blob/770b53eebacf2719ad813b849517b8c281eb8eef/package.json#L24

https://laymonage.com/posts/giscus

I can't fix it without a reproduction.

**Comment by CofCat456** [comment]
Here is a reference https://stackblitz.com/edit/stackblitz-starters-skygff?file=app%2FGiscus.tsx

**Comment by iammukeshm** [comment]
![chrome_7iAtYjMDXx](https://github.com/giscus/giscus-component/assets/31455818/faa41301-4c55-4814-becd-3d95416f9930)
This is the error i see on console. giscus component is not loading for me as well after upgrading to nextjs 14.1.

**Comment by shenlu89** [comment]
I got the same error with `giscus` when using Next.js v14.1.0

![image](https://github.com/giscus/giscus-component/assets/32006082/cca64f2c-6ca1-4d5b-8528-43309509c350)

**Comment by shenlu89** [comment]
> Is there any solution？

https://github.com/giscus/giscus-component/issues/1976#issuecomment-1937404874

**Comment by chsami** [comment]
Confirmed that this is not working with next 14.1

`    <GiscusComponent
      id={COMMENTS_ID}
      // @ts-ignore
      repo={repo}
      repoId={repositoryId}
      category={category}
      categoryId={categoryId}
      mapping={mapping}
      reactionsEnabled={reactions}
      emitMetadata={metadata}
      inputPosition={inputPosition}
      theme={commentsTheme}
      lang={lang}
      loading="lazy"
    />`

<img width="480" alt="image" src="https://github.com/giscus/giscus-component/assets/23292806/3bef9b37-15b7-40fb-a38d-e451875a5fb5">

**Comment by laymonage** [comment]
Looks like the dual CommonJS+ESM support caused this issue. The package is now ESM-only as of v3.0.0. Please try installing that version and see if it works. Thanks!
