### ISSUE TITLE
Add support to react 19.0.0

### ISSUE THREAD

**Issue by shenxiangzhuang** [giscus/giscus-component#2195]
https://github.com/giscus/giscus-component/blob/6fa96022196bf926d79057b4b1cb5746bd213580/react/package.json#L28-L29

Shall we add support to react 19.0.0?

**Comment by laymonage** [comment]
Sure, I think it makes sense!

**Comment by laymonage** [comment]
v3.1.0 is out, which should allow you to use React 19. Please try it out, thanks!
