### ISSUE TITLE
Not able to style with Tailwind CSS

### ISSUE THREAD

**Issue by shinokada** [giscus/giscus-component#26]
**Describe the bug** A clear and concise description of what the bug is.

Thanks for your work.

I'd like to add a dark mode using Tailwind CSS.
[My demo site using Giscus.](https://svelte-flow.vercel.app/modals/small)

I added:

```
<div class="giscus dark:bg-gray-800 dark:text-white"></div>
```

But when I change the mode it doesn't work.

How can I use Tailwind CSS?

**Comment by danestves** [comment]
<img width="906" alt="CleanShot 2022-02-06 at 23 57 57@2x" src="https://user-images.githubusercontent.com/31737273/152722329-c1c50342-4f48-4123-b796-9c9ea155ec98.png">

You must add a custom theme, but that is experimental for now, so, use it at your own risk
