### ISSUE TITLE
Without  the class giscus, it shows globally.

### ISSUE THREAD

**Issue by shinokada** [giscus/giscus-component#27]
**Describe the bug** A clear and concise description of what the bug is.

I just added script tag in the `__layout.svelte`.

I didn't add any `giscus` class or div. But it shows everywhere on my site.

[https://svelte-flow.vercel.app/](https://svelte-flow.vercel.app/)

**Comment by laymonage** [comment]
This is expected behavior. Per the documentation,

> Add the following `<script>` tag to your website's template where you want the comments to appear. If an element with the class `giscus` exists, the comments will be placed there instead.

By default, it creates a `<div class="giscus">` where the `<script>` tag is placed unless it already exists. You shouldn't put it in `__layout.svelte`. Only put it in a layout where you want the comments to appear.

**Comment by shinokada** [comment]
Svelte allows to add only on `script` tag in a file. If I add giscus code in the script tag with other code, it omits an error.
What is the best solution?

**Comment by laymonage** [comment]
Use the dedicated Svelte component (`npm install @giscus/svelte`) instead of the client script.

or...

I'm also building a [native web component](https://www.npmjs.com/package/giscus) but that's still very early in development and I haven't published the repo. You should be able to just use it, e.g.

```svelte
<script lang="ts">
  import "giscus";
</script>

<giscus-widget
  repo="giscus/giscus"
  repoid="MDEwOlJlcG9zaXRvcnkzNTE5NTgwNTM="
  category="General"
  categoryid="MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyNzk2NTc1"
  mapping="specific"
  term="Welcome to giscus!"
  reactionsenabled="1"
  emitmetadata="0"
  inputposition="top"
  theme="light"
  lang="en"
/>
```
