### ISSUE TITLE
Svelte component doesn't work

### ISSUE THREAD

**Issue by jestarray** [giscus/giscus-component#7]
https://jestlearn.com/how_to_code/#discuss/structs

On chrome I get:
```
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
```
and on firefox i get:
```
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
```
Here is my source code: https://github.com/jestarray/jestlearn/blob/main/src/Discussions.svelte

I tried both using the Giscus svelte component which doesn't work at all, and the `<script>` tag which only works on localhost and not in deployment... seems like it doesn't even load the <script> in deployment strangely according to the network tab..
My repo https://github.com/jestarray/howtocode/discussions is public and has discussions enabled so I'm unsure what the problem is.

**Comment by jestarray** [comment]
Nope, tried with the latest version and even wiped `node_modules` but its still not working on my project a least... `<script>` is still working though. I haven't tested it in production just yet, just localhost as you can see

https://user-images.githubusercontent.com/34615798/152651934-cd32f1b8-2768-40a9-b352-643477266424.mp4

.

**Comment by laymonage** [comment]
Does anything show up on the browser console?

**Comment by jestarray** [comment]
Nope, just the same old warning messages as last time:

On firefox: `Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.`

On chrome: `Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.`

I'll try to come up with a small reproducible case

**Comment by laymonage** [comment]
Please try with v2.0.0 and report back if the issue still happens.
