### ISSUE TITLE
Handle layout shift

### ISSUE THREAD

**Issue by winston0410** [giscus/giscus-component#74]
Is it possible to prevent layout shift of loading the frame by setting `width` and `height` initially? Right now the component doesn't accept `width` or `height`.

**Comment by laymonage** [comment]
I suppose you could wrap the element with a `div` that has a `min-height` of at least `150px` and `width` of `100%`? The web component has `width: 100%` in it and the height is determined by the height of the contents, so you can create an element that wraps it to whatever width and height you like.

**Comment by laymonage** [comment]
You can now style the iframe directly by using `::part(iframe)`[^1]. Example:

https://github.com/giscus/giscus-component/blob/a0efc63b3c6f0804a377366c6615ec0aa8a2ffda/demo/react/src/styles.css#L1-L5

[^1]: https://developer.mozilla.org/en-US/docs/Web/CSS/::part
