### ISSUE TITLE
Inconsistent styling resulting from most recent changes

### ISSUE THREAD

**Issue by farlowdw** [giscus/giscus-component#778]
It looks like the most recent updates resulted in improper styling being applied. For example, the currently live [giscus-component.vercel.app](https://giscus-component.vercel.app/) page renders the comments section as follows (correct):

![giscus-correct](https://user-images.githubusercontent.com/73953353/201483388-bf5f5c6a-1edd-446b-9103-626a440c58c4.png)

But if I try to use the component library for, say, React ([giscus-component.vercel.app/react](https://giscus-component.vercel.app/react)), then I am seeing the following (incorrect):

![giscus-incorrect](https://user-images.githubusercontent.com/73953353/201483504-edabe23a-14cd-4570-8a88-8d941e172bb4.png)

What can be done to revert the styling back to what it was previously for the different component libraries?

**Comment by farlowdw** [comment]
It looks like [another user referenced this in a comment](https://github.com/giscus/giscus/issues/777#issuecomment-1310483625) about this seemingly being a browser-related issue. The behavior highlighted above appears on Chrome, Edge, Opera, Brave, etc., but the "correct" behavior is exhibited on Firefox.

**Comment by laymonage** [comment]
Please try updating to v2.2.3 and check if the issue is fixed.

**Comment by farlowdw** [comment]
Thank you. I ran into a webpack issue after making the update (I'm using a Docusaurus-powered site and trying to use giscus to enable comments for doc posts and blog entries):

```
Module not found: Error: Can't resolve 'react/jsx-runtime' in '/.../node_modules/@giscus/react/dist'
```

For anyone else facing the same issue, I [wrote a post](https://dwf.dev/blog/2022/11/12/updating-docusaurus-webpack-config) detailing how I overcame the problem (I realize my specific problem is obviously off-topic for this issue). Thanks for responding and for all of your work.
