### ISSUE TITLE
[bug] React component failed to build

### ISSUE THREAD

**Issue by MuYunyun** [giscus/giscus-component#783]
### What happened?

When I update giscus-react from 2.2.2 to 2.2.3, my [react project](https://github.com/MuYunyun/create-react-doc) building crashed:

![image](https://user-images.githubusercontent.com/19354791/202755070-4bd950c6-b98b-4a58-bd86-c3cf4fb6602d.png)

I'm not sure if my case is the same with https://github.com/giscus/giscus-component/issues/782.

### Debug

I'm using Giscus in [such way](https://github.com/MuYunyun/create-react-doc/blob/main/packages/crd-seed/layout/index.js#L5):

```js
const Giscus = require('@giscus/react')
```

Then I print 'Giscus' in project with console.log:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/19354791/202756127-03e9e718-27c9-4dc1-9877-3d788fd51e79.png">

giscus-react in 2.2.2 it prints a function as follow:

![image](https://user-images.githubusercontent.com/19354791/202756433-f0ad93af-a1ce-4a8e-80df-ae26f0687d46.png)

giscus-react in 2.2.3 it prints a path as follow:

![image](https://user-images.githubusercontent.com/19354791/202759308-20798ce2-f547-403b-8dac-827300ec9bfc.png)

### Environment

|  Software     |  Version(s)     |
| :--- | :--- |
|   React    |   18.0.0    |
|    Node   |    16.13.0   |

### Others

【advice】If the build product changes [commit](https://github.com/giscus/giscus-component/commit/c35cd147626e1954739a2d23d90efaedc7d792ad), is it better to upgrade with BREAK CHANGE?

**Comment by laymonage** [comment]
Fixed in #810, released in v2.2.4.
