### ISSUE TITLE
How to disable resizing of iframe height ??

### ISSUE THREAD

**Issue by NithinKuruba** [giscus/giscus-component#980]
I am rendering multiple discussions in form of giscus widgets in my react app. Each giscus widget is a child of an Accordion component created using react-bootstrap. When I open one accordion component to view giscus widget, the height of the iframe of already opened one re-adjusts and gets cropped, which is a weird behaviour. Is there a way to stop this resizing of the iframe height??

**Comment by laymonage** [comment]
You can wrap the iframe in a container and limit that container's height, as shown in https://github.com/giscus/giscus-component#changing-the-iframe-styles.
